export const CELL = {
  COVERED: 'covered',
  MINES0: 'mines0',
  MINES1: 'mines1',
  MINES2: 'mines2',
  MINES3: 'mines3',
  MINES4: 'mines4',
  MINES5: 'mines5',
  MINES6: 'mines6',
  MINES7: 'mines7',
  MINES8: 'mines8',
  MINE_HIT: 'mine-hit',
  MINE_MISFLAGGED: 'mine-misflagged',
  MINE: 'mine',
  FLAG: 'mineflag',
  QUESTION: 'question',
}
